### ISSUE TITLE
Current commit doesn't compile

### ISSUE THREAD

**Issue by r2d2rigo** [xfixium/GMare#5]
There seem to be files missing from the current commit that render the project unable to be compiled - mainly, `PyxUnitNumericUpDown.cs` and some image resources like `cursor_brush`, `cursor_fill`, etc.

Can this be addressed or are these files definitely lost? If they are I could attempt to patch the missing changes by decompiling the latest working release.

**Comment by xfixium** [comment]
I'm a "little" late to this issue lol. Codeplex was closing, and I scrambled to get the source here in a hurried manner. My apologies. However, if there is one thing I'm good at, it's taking care of my source code, and I uploaded the missing files. Thank you for branching, and fixing the issues.
