### ISSUE TITLE
Do you have GMare 2.0 or 1.19?

### ISSUE THREAD

**Issue by yoiryosaturn** [xfixium/GMare#8]
I am using GMS1.4 because I am more familiar with it + I don't want to buy a monthly/yearly subscription for GMS2. I searched the Internet for a way to get a better room editor and then I found this. You've been talking since 2016 of wanting to upload 1.19, but looks like you never did because GMS2 released by the time. I thought it'd be fine to just use the 1.18 version, but I am hit with the reality that I cannot even import rooms or objects or any shit, so for me, this program is practically useless. I would really love to have access to GMare 2.0 or 1.19 if you still have it. Thanks.

**Comment by xfixium** [comment]
Hmmm, this app is dirt old. XD I know I wrote an importer. Most likely it wasn't fully tested. I kinda just dumped the stable source here. I went to my actual dev source and made a build. Warning, I have no clue what state the code is in, it may be very fuct. But the import GM Project option SEEMS to work at least. I take no responsibility for your sadness/uncontrolled rage if it doesn't work.

Dev Build Binaries Download:
https://www.pyxosoft.com/projects/gmare/downloads/gmare_04_25_2023.zip

**Comment by yoiryosaturn** [comment]
Thanks but it doesn't even import. Nevermind I guess and thank you

**Comment by xfixium** [comment]
I forgot to mention, you could import your maps in by making them an image, and then use the import from image feature. You choose an image, then click the compile button. Once that's complete, you can import the instances through the import objects button. A little more work, but another approach.
